version: "3.7"

services:
  api:
    image: devpies/go-delve-reload:api
    secrets:
      - postgres_db
      - postgres_user
      - postgres_passwd
    environment:
      CGO_ENABLED: 0
      API_DB_HOST: db
      API_WEB_ADDRESS: :4000
      API_DB_DISABLE_TLS: "false"
      API_WEB_PRODUCTION: "true"
      API_WEB_FRONTEND_ADDRESS: https://gdr.devpie.io/
      POSTGRES_DB: /run/secrets/postgres_db
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_passwd
    deploy:
      labels:
        - traefik.frontend.rule=Host:api.gdr.devpie.io
        - traefik.enable=true
        - traefik.port=4000
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.users=devpie:$$apr1$$cRAoevPx$$fMQ591BUA36Tq6Vh62QqX0
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - traefik-public
      - postgres-network

  client:
    image: devpies/go-delve-reload:client
    deploy:
      labels:
        - traefik.frontend.rule=Host:gdr.devpie.io
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.users=devpie:$$apr1$$cRAoevPx$$fMQ591BUA36Tq6Vh62QqX0
    networks:
      - traefik-public

  db:
    image: postgres:11.6
    secrets:
      - postgres_db
      - postgres_user
      - postgres_passwd
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/seed
    networks:
      - postgres-network

networks:
  postgres-network:
    external: true
  traefik-public:
    external: true

volumes:
  postgres-db:

secrets:
  postgres_db:
    external: true
  postgres_passwd:
    external: true
  postgres_user:
    external: true
